### ISSUE TITLE
Unable to set a breakpoint on start.

### ISSUE THREAD

**Issue by eugeneo** [eugeneo/node#6]
Maybe we will also need a special breakpoints for newly loaded modules. Kind of pending breakpoints in GDB?

**Comment by ofrobots** [comment]
I think @matthewloring may have a solution for this.

**Comment by matthewloring** [comment]
My work to enable this is here: https://github.com/repenaxa/node/pull/6

**Comment by eugeneo** [comment]
@matthewloring Thanks, I reviewed you code. It mostly deals with waiting for another process to start - I already had the code for that as I was basing on the original node debugger code.

@ofrobots Can you please review the change? What happens here is that setting that dummy listener resets the listener V8Inspector set. I tested the code after removing the offending line (both inspector and node debugger) and did not see any exceptions.
